let date=new Date()
console.log(date)
console.log(date.toString())
console.log(date.toDateString())
console.log(date.toLocaleDateString())
console.log(date.toTimeString())
console.log(date.toJSON())
